### ISSUE TITLE
Can you please generate include/zel/z80_instruction_types.h

### ISSUE THREAD

**Issue by abelykh0** [stevecheckoway/libzel#1]
Can you please generate include/zel/z80_instruction_types.h. I have trouble running make,

```
perl tables/gen.pl tables/fd_prefix.spec > tables/fd_prefix.tab
8
make: *** [Makefile:75: tables/fd_prefix.tab] Error 25
```

**Comment by stevecheckoway** [comment]
Sure. I added all of the generated files to the repo. I'm not really sure what the underlying issue is though.

**Comment by abelykh0** [comment]
> 
> 
> Sure. I added all of the generated files to the repo. I'm not really sure what the underlying issue is though.

Thanks! I don't know perl at all, so I can't explain why it is failing for me. I tried on Ununtu 20.04.

**Comment by stevecheckoway** [comment]
I haven't used Perl in years, but I'll give Ubuntu 20.04 a try and see if I can figure it out. Thanks!

**Comment by abelykh0** [comment]
Thanks! FYI, used your emulator here https://github.com/abelykh0/esp32-z80emu. Unfortunately, I had to modify the code a little, as it looks like I couldn't access iff1, iff2, interrupt_mode, and also there's no convenient access to byte registers.

**Comment by stevecheckoway** [comment]
That's really great! Thanks for letting me know.
